### ISSUE TITLE
titlebar: false is not working

### ISSUE THREAD

**Issue by kelvinkoko** [davidfig/window-manager#12]
Sorry just have one more question. I suppose setting `tilebar: false` will hide the title bar for that window, but it seems no effect (Or i understand this field incorrectly?)

p.s. I can achieve the "hide titlebar" by setting titlebarHeight: 0px though : )

**Comment by davidfig** [comment]
Another good catch. options.titlebar now works properly in v1.3.0

**Comment by kelvinkoko** [comment]
Thank you very much again!~
